CREATE TABLE {db}.{schema}.DimEmployees_SCD1(
	EmployeeID_PK_SK int PRIMARY KEY IDENTITY(1,1),
	EmployeeID_NK int,
	LastName varchar(20) NOT NULL,
	FirstName varchar(10)  NOT NULL,
	Title varchar(30) NULL,
	TitleOfCourtesy varchar(25) NULL, 
	BirthDate datetime NULL,
	HireDate datetime NULL,
	Address varchar(60) NULL,
	City varchar(15) NULL,
	Region varchar(15) NULL,
	PostalCode varchar(10) NULL,
	Country varchar(15) NULL,
	HomePhone varchar(24) NULL,
	Extension varchar(4) NULL,
	Notes varchar(500) NULL,
	ReportsTo int NULL,
	PhotoPath varchar(255) NULL,
	FOREIGN KEY(ReportsTo) references DimEmployees_SCD1(EmployeeID_PK_SK)
);