-- MERGE {db_dim}.{schema_dim}.{table_dim} AS DST -- destination
-- USING {db_rel}.{schema_rel}.{table_rel} AS SRC -- source
-- ON ( SRC.ProductID = DST.ProductID_NK )
-- WHEN NOT MATCHED THEN -- there are IDs in the source table that are not in the destination table
--   INSERT (ProductID_NK, ProductName, SupplierID, CategoryID, QuantityPerUnit, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel, Discontinued)
--   VALUES (SRC.ProductID, SRC.ProductName, SRC.SupplierID, SRC.CategoryID, SRC.QuantityPerUnit, SRC.UnitPrice, SRC.UnitsInStock, SRC.UnitsOnOrder, SRC.ReorderLevel, SRC.Discontinued)
-- WHEN MATCHED AND (
--   ISNULL(DST.ProductName, '') <> Isnull(SRC.ProductName, ''))
--   THEN
--     UPDATE SET
--         DST.ProductName = SRC.ProductName;
